-- Auto-generated from schema-map-postgres.yaml (map@74ce4f4)
-- engine: postgres
-- table:  sessions

CREATE TABLE IF NOT EXISTS sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  token_hash BYTEA NOT NULL,
  token_hash_key_version VARCHAR(64) NULL,
  token_fingerprint BYTEA NULL,
  token_issued_at TIMESTAMPTZ(6) NULL,
  user_id BIGINT NULL,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  version INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT chk_sessions_version CHECK (version >= 0),
  last_seen_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  expires_at TIMESTAMPTZ(6) NULL,
  failed_decrypt_count INTEGER NOT NULL DEFAULT 0,
  last_failed_decrypt_at TIMESTAMPTZ(6) NULL,
  revoked BOOLEAN NOT NULL DEFAULT FALSE,
  ip_hash BYTEA NULL,
  ip_hash_key_version VARCHAR(64) NULL,
  user_agent VARCHAR(1024) NULL,
  session_blob BYTEA NULL,
  CONSTRAINT uq_sessions_token_hash UNIQUE (token_hash),
  CONSTRAINT chk_sessions_failed_decrypt_count CHECK (failed_decrypt_count >= 0),
  CONSTRAINT chk_sessions_expires_after_created CHECK (expires_at IS NULL OR expires_at >= created_at)
);
